IF OBJECT_ID('user_totp', 'U') IS NOT NULL DROP TABLE user_totp;

CREATE TABLE user_totps (
    id UNIQUEIDENTIFIER PRIMARY KEY,
    user_id UNIQUEIDENTIFIER NOT NULL UNIQUE FOREIGN KEY REFERENCES users(id) ON DELETE CASCADE,
    secret NVARCHAR(MAX) NOT NULL,
    is_verified BIT NOT NULL DEFAULT 0,
    created_at DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME2
);
