DROP TABLE IF EXISTS user_api_keys_roles;
DROP TABLE IF EXISTS user_api_keys;
DROP TABLE IF EXISTS user_passkey;

CREATE TABLE user_api_keys (
    id SERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(64) NOT NULL,
    name_upcase VARCHAR(64) NOT NULL,
    key_hint VARCHAR(16) NOT NULL,
    key_digest VARCHAR(1024) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    is_revoked BOOLEAN NOT NULL DEFAULT FALSE,
    comment VARCHAR(512),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE user_passkeys (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    credential_id BYTEA NOT NULL,
    data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
